### ISSUE TITLE
Error: image library/modx:latest not found

### ISSUE THREAD

**Issue by eightnoneone** [vh/docker-modx#11]
$ docker-compose up
Pulling db (mysql:latest)...
latest: Pulling from library/mysql
386a066cd84a: Pull complete
827c8d62b332: Pull complete
de135f87677c: Pull complete
05822f26ca6e: Pull complete
63ddbddf6165: Pull complete
15fe0fbc587e: Pull complete
93e74acdb291: Pull complete
11c2df82e984: Pull complete
d42a9e6a85c8: Pull complete
e7fb2f3afd87: Pull complete
30724006a583: Pull complete
Digest: sha256:89cc6ff6a7ac9916c3384e864fb04b8ee9415b572f872a2a4cf5b909dbbca81b
Status: Downloaded newer image for mysql:latest
Pulling web (modx:latest)...
Pulling repository docker.io/library/modx
ERROR: Error: image library/modx:latest not found

**Comment by edlerarts** [comment]
You should use `image: budjizu/modx` instead of `image: modx`

**Comment by vh** [comment]
At this moment yes
@rthrash https://hub.docker.com/r/modx/revolution/ is that will be official docker repo?
