### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by muzzwood** [vh/docker-modx#12]
Hi! 

I've created the docker-compose.yml file.

I then type the command 'docker-compose up'

It completes the pulls for library/mysql then says the following:
`Pulling web (modx:latest)...
Pulling repository docker.io/library/modx
ERROR: Error: image library/modx:latest not found`

Am I going wrong somewhere or does the modx library not exist?
Thanks!

**Comment by muzzwood** [comment]
Turns out there is no official MODX docker image so unsure as to the purpose of this repo. Closing.

**Comment by Omeryl** [comment]
Hey @digitalpenguin,

At some point soon we are planning to push something out to the Docker repo, just have to wait on some planning stuff first. Sorry!

**Comment by vh** [comment]
@digitalpenguin current workaround can be:
- clone this repo
- run `docker build -t modx .` for image you need (apache or fpm)
- run docker-compose

**Comment by muzzwood** [comment]
@Omeryl No worries! Looking forward to it ;)

@vh Thanks! Will give that a go!
