### ISSUE TITLE
How can I setup MODX_PREFIX and then insert data from my dump file?

### ISSUE THREAD

**Issue by me-kou** [vh/docker-modx#19]
Your docker-modx is very helpful..
But now I want to do some correction to make it fit for my prod environment..
I almost know nothing about php so I stuck in how to set up MODX_PREFIX..
And I want to insert my data into modx database(which table with prefix like 'modx_')..
I have already created a dump file..
Hope I can get your reply! 
Thank you a lot !

**Comment by vh** [comment]
Hi! Just set MODX_TABLE_PREFIX env variable for that. :)
