### ISSUE TITLE
Move repository to the modxcms organization namespace

### ISSUE THREAD

**Issue by vh** [vh/docker-modx#2]

**Comment by vh** [comment]
@Mark-H can we resolve this issue? ;)

**Comment by Mark-H** [comment]
This is not something I can do unfortunately...

**Comment by Mark-H** [comment]
Would you be willing to still lead/maintain this effort if the repo was moved?

**Comment by vh** [comment]
Yep. I can be maintainer of this repo / docker image.

**Comment by vh** [comment]
@Mark-H it seem issue #4 has been resolved with new MODX 2.5 and PHP 7 :)

**Comment by rthrash** [comment]
Let me know when you want to move it and I'll help make that happen.

**Comment by vh** [comment]
@rthrash I'm ready to move it

**Comment by vh** [comment]
@rthrash bump

**Comment by rthrash** [comment]
Hi Vadim, you can initiate the change by sending it to my account, and I'll
get it moved to the organization. Thanks for following up on this and for
your patience!
On Tue, Jun 7, 2016 at 3:15 AM Vadim Homchik notifications@github.com
wrote:

> @rthrash https://github.com/rthrash bump
> 
> —
> You are receiving this because you were mentioned.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/vh/docker-modx/issues/2#issuecomment-224211228, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAOS_Y9UPprloyLs7BkG6fPqXQc4_Jwqks5qJSi6gaJpZM4HpOyR
> .
> 
> ## 

## 

[image: photo]
_Ryan Thrash_
Co-founder & CEO, MODX
p:+1 214-682-5050 | e:ryan@modx.com | w:http://modx.com
http://us.linkedin.com/in/ryanthrash  http://twitter.com/rthrash
http://facebook.com/rthrash

**Comment by vh** [comment]
@rthrash no problem! I've started transfer.

**Comment by rthrash** [comment]
It seems to have expired. Let's try again to @rthrash?

**Comment by vh** [comment]
@rthrash done!
